[tool.black]
line-length=88
target-version = ["py39", "py310", "py311", "py312", "py313"] 

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]

[tool.mypy]
python_version = "2.7"
warn_return_any = true
warn_unused_configs = true